### ISSUE TITLE
Some configuration is still compiled into the contract

### ISSUE THREAD

**Issue by tbfleming** [eoscommunity/Eden#167]
```
            -DEDEN_ATOMIC_ASSETS_ACCOUNT=${EDEN_ATOMIC_ASSETS_ACCOUNT}
            -DEDEN_ATOMIC_MARKET_ACCOUNT=${EDEN_ATOMIC_MARKET_ACCOUNT}
            -DEDEN_SCHEMA_NAME=${EDEN_SCHEMA_NAME}
```

These should move to the `genesis` action

**Comment by swatanabe** [comment]
I left these alone because they usually should not need to be changed.
- The atomicassets accounts only needs to be changed when deploying the contract to a different chain.
- The schema name only needs to be changed for testing, i.e. after changing the schema in an incompatible way.  This should never happen in production.

**Comment by brandonfancher** [comment]
I'm closing this for now...until we encounter this as a pain point.
