### ISSUE TITLE
eden: rpc endpoint load balancing and failover

### ISSUE THREAD

**Issue by brandonfancher** [eoscommunity/Eden#243]
When the primary RPC node isn't responding, fallback to another. We should have multiple RPC endpoints in our env vars and config. And we should also consider randomizing the order in which they're used.

React Query allows you to tap into their retry logic--globally and on a query-by-query basis: https://react-query.tanstack.com/guides/query-retries

That might be a good place to start.

Requirements:

- When you first visit the page, the RPC provider you're using should be randomly selected. (load balancing)
- If an RPC call fails for one reason or another (including you kicked off too many requests and got put in purgatory for 10 minutes), the next RPC endpoint should be promoted and used (until there's a problem with that one or everything is re-randomized when you reload the web app)

**Comment by sparkplug0025** [comment]
I think we need more thought on this... The fallback for the queries will work fine when we add custom retries on React-Query but since we are not using mutations for broadcasting the transactions we will not have the same behavior when signing transactions... 

I think we could do that by wrapping our transactions broadcasting after signing it with a react-query mutation.

**Comment by cool-ant** [comment]
@sparkplug0025 here are the production endpoints I've now vetted. Please use these
eos.dfuse.eosnation.io
eos.greymass.com
api.eossweden.org
mainnet.eosamsterdam.net
